# Generated by Django 5.0.3 on 2024-03-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='publishDate',
            new_name='created_at',
        ),
    ]
